title: Ben Pitler # your name (or website title) here
logo: "/images/bp-avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Human rights defender and University of Washington MBA candidate, data science/analytics track. Passionate about using data science to achieve justice. 
  <br><br>
  This portfolio details my use of data science to investigate and document violations of international human rights law. Please direct all questions and requests to collaborate to <a href="ds4hrbp@protonmail.com">ds4hrbp@protonmail.com</a> 
 
  <br><br>
  <a href="https://www.linkedin.com/in/ben-pitler/">LinkedIn</a> <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
