title: Ben Pitler # your name (or website title) here
logo: "/images/bp-avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Human rights defender and University of Washington MBA candidate, data science/analytics track. Passionate about using data science to achieve justice. 
  <br><br>
  This portfolio details my use of data science to investigate and document violations of international human rights law. Please direct all questions and requests to collaborate to <a href="benpitler@gmail.com">benpitler@gmail.com</a> or <a href="bpitler@uw.edu">bpitler@uw.edu</a> 
 
  <br><br>
  <a href="https://www.linkedin.com/in/ben-pitler/">LinkedIn</a>
  <a href="https://www.cargocollective.com/ibnyemin/">Photography portfolio</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
